# Generated by Django 3.0.6 on 2020-12-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='career_profile',
            field=models.URLField(blank=True, help_text='URL to your career profile. E.g. LinkedIn, Indeed etc.'),
        ),
    ]
